"""
PRISM Legacy Data Generator — SQL INSERT output
Generates realistic PRISM pension data with known data quality issues.
Output: init/02_seed.sql with schema-qualified INSERT statements.
"""
import random, datetime, os

random.seed(42)

N_MEMBERS = 100
MIGRATION_BOUNDARY = datetime.date(1998, 1, 1)
SSN_BOUNDARY = datetime.date(2001, 1, 1)
BIRTH_DT_ERROR_RATE = 0.15

EMPLOYERS = [
    ("CITYMAIN", "City of Riverside", "MUNI"),
    ("CNTY01",   "Riverside County", "CNTY"),
    ("SCH001",   "Unified School District", "SCHL"),
    ("UTIL01",   "Municipal Utilities", "SPEC"),
    ("FIRE01",   "Fire District No. 4", "SPEC"),
    ("PARK01",   "Parks & Recreation", "MUNI"),
]

# ---------------------------------------------------------------------------
# SQL helpers
# ---------------------------------------------------------------------------

def sql_str(val):
    """Wrap a string value for SQL. Returns NULL for None."""
    if val is None:
        return "NULL"
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"

def sql_num(val):
    """Numeric literal or NULL."""
    if val is None:
        return "NULL"
    return str(val)

def sql_date(val):
    """Date literal or NULL. Accepts date objects or strings."""
    if val is None:
        return "NULL"
    if isinstance(val, datetime.date):
        return f"'{val.isoformat()}'"
    return f"'{val}'"

def sql_ts(val):
    """Timestamp literal or NULL."""
    if val is None:
        return "NULL"
    if isinstance(val, datetime.datetime):
        return f"'{val.strftime('%Y-%m-%d %H:%M:%S')}'"
    if isinstance(val, datetime.date):
        return f"'{val.isoformat()} 00:00:00'"
    return f"'{val}'"

# ---------------------------------------------------------------------------
# Data helpers (unchanged logic from original generator)
# ---------------------------------------------------------------------------

def rand_date(start_yr, end_yr):
    if start_yr > end_yr:
        end_yr = start_yr
    start = datetime.date(start_yr, 1, 1)
    end = datetime.date(end_yr, 12, 31)
    delta = (end - start).days
    if delta <= 0:
        return start
    return start + datetime.timedelta(days=random.randint(0, delta))

def format_birth_dt(dt, orig_sys):
    if orig_sys == "OPUS" and random.random() < BIRTH_DT_ERROR_RATE:
        return f"{dt.month:02d}{dt.day:02d}{dt.year:04d}"  # wrong: MMDDYYYY
    return dt.strftime("%Y%m%d")

def format_ssn(s, hire_dt):
    return f"{s[:3]}-{s[3:5]}-{s[5:]}" if hire_dt < SSN_BOUNDARY else s

def gen_ssn():
    return str(random.randint(100000000, 999999999))

# ---------------------------------------------------------------------------
# Name pools
# ---------------------------------------------------------------------------

first_names = [
    "James","Mary","Robert","Patricia","Michael","Linda","William","Barbara",
    "David","Elizabeth","Richard","Jennifer","Joseph","Maria","Thomas","Susan",
    "Charles","Margaret","Christopher","Dorothy","Daniel","Lisa","Nancy"
]
last_names = [
    "Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis",
    "Wilson","Taylor","Anderson","Thomas","Jackson","White","Harris","Martin",
    "Thompson","Young","Robinson","Lewis","Walker","Hall","Allen","King"
]

# ---------------------------------------------------------------------------
# Collect SQL statements
# ---------------------------------------------------------------------------
sql_lines = []

def emit(line):
    sql_lines.append(line)

# Header
emit("-- ============================================================")
emit("-- PRISM seed data — auto-generated by prism_data_generator.py")
emit("-- Deterministic seed: 42")
emit(f"-- Members: {N_MEMBERS}")
emit("-- ============================================================")
emit("")
emit("SET search_path TO src_prism;")
emit("")

# ---------------------------------------------------------------------------
# Reference data: PRISM_EMPR_LIST
# ---------------------------------------------------------------------------
emit("-- PRISM_EMPR_LIST")
for empr_cd, empr_nm, empr_typ in EMPLOYERS:
    emit(
        f"INSERT INTO src_prism.PRISM_EMPR_LIST "
        f"(EMPR_CD, EMPR_NM, EMPR_TYP_CD, EMPR_STATUS, JOIN_DT, CONTRIB_RATE) VALUES "
        f"({sql_str(empr_cd)}, {sql_str(empr_nm)}, {sql_str(empr_typ)}, 'A', '1991-01-01', 0.1200);"
    )
emit("")

# ---------------------------------------------------------------------------
# Reference data: PRISM_MISC_CODES (already seeded in DDL, add extras)
# ---------------------------------------------------------------------------
emit("-- PRISM_MISC_CODES — additional codes beyond status codes in DDL")
plan_codes = [
    ("PLAN", "DB_MAIN", "Defined Benefit — Main Plan", "DB Main",  "1991-01-01"),
    ("PLAN", "DB_T2",   "Defined Benefit — Tier 2",    "DB Tier2", "2010-01-01"),
    ("JOBCL", "ADMIN",  "Administrative",               "Admin",    "1991-01-01"),
    ("JOBCL", "PROF",   "Professional",                  "Prof",     "1991-01-01"),
    ("JOBCL", "SAFTY",  "Public Safety",                 "Safety",   "1991-01-01"),
    ("JOBCL", "MGMT",   "Management",                    "Mgmt",     "1991-01-01"),
    ("TRSN",  "VOL",    "Voluntary Termination",         "Vol Term", "1991-01-01"),
    ("TRSN",  "INVL",   "Involuntary Termination",       "Invol",    "1991-01-01"),
    ("TRSN",  "RET",    "Retirement",                    "Retire",   "1991-01-01"),
    ("TRSN",  "DEAT",   "Death",                         "Death",    "1991-01-01"),
]
for code_type, code_val, code_desc, short_desc, eff_dt in plan_codes:
    emit(
        f"INSERT INTO src_prism.PRISM_MISC_CODES "
        f"(CODE_TYPE, CODE_VAL, CODE_DESC, SHORT_DESC, EFF_DT, END_DT, SORT_SEQ, NOTES) VALUES "
        f"({sql_str(code_type)}, {sql_str(code_val)}, {sql_str(code_desc)}, "
        f"{sql_str(short_desc)}, '{eff_dt}', NULL, NULL, NULL);"
    )
emit("")

# ---------------------------------------------------------------------------
# Reference data: PRISM_PLAN_PARAMS
# ---------------------------------------------------------------------------
emit("-- PRISM_PLAN_PARAMS")
plan_params = [
    (1, "DB_MAIN", "1991-01-01", None, 0.0200, 65.0, 55.0, 0.0600, 0.3000, 60, 0.7500, 800.00, 5.0, 0.0850, 0.1200, 0.0300),
    (2, "DB_MAIN", "2003-01-01", None, 0.0200, 65.0, 55.0, 0.0600, 0.3000, 36, 0.7500, 800.00, 5.0, 0.0850, 0.1200, 0.0300),
    (3, "DB_T2",   "2010-01-01", None, 0.0180, 67.0, 57.0, 0.0600, 0.3000, 60, 0.7500, 800.00, 5.0, 0.0900, 0.1200, 0.0200),
]
for p in plan_params:
    emit(
        f"INSERT INTO src_prism.PRISM_PLAN_PARAMS "
        f"(PARAM_ID, PLAN_CD, EFF_DT, END_DT, BENEFIT_MULT, NRM_RET_AGE, ERY_RET_AGE, "
        f"ERY_PENALTY_RT, ERY_MAX_PEN, FAS_PERIOD_MO, MAX_BENEFIT_PCT, MIN_BENEFIT_AMT, "
        f"VESTING_YRS, CONTRIB_RATE_EE, CONTRIB_RATE_ER, COLA_CAP_PCT) VALUES "
        f"({p[0]}, {sql_str(p[1])}, {sql_date(p[2])}, {sql_date(p[3])}, "
        f"{sql_num(p[4])}, {sql_num(p[5])}, {sql_num(p[6])}, {sql_num(p[7])}, "
        f"{sql_num(p[8])}, {sql_num(p[9])}, {sql_num(p[10])}, {sql_num(p[11])}, "
        f"{sql_num(p[12])}, {sql_num(p[13])}, {sql_num(p[14])}, {sql_num(p[15])});"
    )
emit("")

# ---------------------------------------------------------------------------
# Generate members and related data
# ---------------------------------------------------------------------------
members = []
calcs = []
sal_annual = []
sal_period = []

ann_id = prd_id = calc_id = spell_id = job_seq = 1

emit("-- PRISM_MEMBER")
for i in range(N_MEMBERS):
    mbr_nbr = 10000 + i
    hire_yr = random.randint(1965, 2022)
    hire_dt = rand_date(hire_yr, min(hire_yr + 2, 2022))
    birth_yr = hire_yr - random.randint(22, 45)
    birth_yr = max(birth_yr, 1935)
    birth_dt = rand_date(birth_yr, min(birth_yr + 3, hire_yr - 20))

    orig_sys = "OPUS" if hire_dt < MIGRATION_BOUNDARY else None
    today = datetime.date(2025, 1, 1)
    age = (today - birth_dt).days / 365.25
    yos = (today - hire_dt).days / 365.25

    plan_cd = "DB_T2" if hire_dt >= datetime.date(2010, 1, 1) else "DB_MAIN"
    tier = "T2" if plan_cd == "DB_T2" else ("T1" if orig_sys != "OPUS" else None)
    empr = random.choice(EMPLOYERS)
    base_sal = random.randint(38000, 92000)

    ret_dt = death_dt = None
    terminated = on_leave = disability = False
    vested = yos >= 5

    r = random.random()
    if age > 62 and yos > 20 and r < 0.60:
        ret_yr = min(hire_yr + random.randint(25, 35), 2024)
        ret_dt = rand_date(ret_yr, min(ret_yr + 3, 2024))
        if random.random() < 0.08:
            death_yr = min(ret_yr + random.randint(1, 15), 2024)
            death_dt = rand_date(death_yr, min(death_yr + 2, 2024))
    elif r < 0.12 and not ret_dt:
        terminated = True
    elif r < 0.15 and not ret_dt:
        on_leave = True
    elif r < 0.17 and not ret_dt and yos > 5:
        disability = True
        ret_dt = rand_date(max(hire_yr + 5, 2000), min(2024, hire_yr + 30))

    # Status code (overloaded)
    if death_dt:
        status_cd = "D"
    elif disability and ret_dt:
        status_cd = "DI"
    elif ret_dt:
        status_cd = "R"
    elif terminated and vested:
        status_cd = "DE"
    elif terminated:
        status_cd = "I"
    elif on_leave and hire_dt >= datetime.date(2003, 1, 1):
        status_cd = "AL"
    else:
        status_cd = "A"

    ssn = format_ssn(gen_ssn(), hire_dt)
    birth_dt_str = format_birth_dt(birth_dt, orig_sys)
    hire_dt_str = str(hire_dt)
    mid_init = random.choice(["A","B","C","D","E","J","K","L","M","R","S","T", None])
    gndr = random.choice(["M","F",None]) if orig_sys == "OPUS" else random.choice(["M","F"])
    mar_sts = random.choice(["S","M","D","W", None])
    dept_cd = random.choice(["ADM","FIN","IT","OPS","HR","ENG", None])
    job_class = random.choice(["ADMIN","PROF","SAFTY","MGMT", None])
    last_nm = random.choice(last_names)
    first_nm = random.choice(first_names)
    email = f"{first_nm.lower()}.{last_nm.lower()}{mbr_nbr}@example.com" if hire_dt >= datetime.date(2006, 1, 1) else None
    lst_upd = datetime.datetime(2024, random.randint(1,12), random.randint(1,28), random.randint(8,17), random.randint(0,59), 0)

    emit(
        f"INSERT INTO src_prism.PRISM_MEMBER "
        f"(MBR_NBR, LAST_NM, FIRST_NM, MID_INIT, NATL_ID, BIRTH_DT, GNDR_CD, MAR_STS_CD, "
        f"STATUS_CD, HIRE_DT, MBR_TIER, PLAN_CD, EMPR_CD, DEPT_CD, JOB_CLASS_CD, "
        f"ORIG_SYS, EMAIL_ADDR, RET_DT, DEATH_DT, LST_UPD_DT, LST_UPD_USR) VALUES "
        f"({mbr_nbr}, {sql_str(last_nm)}, {sql_str(first_nm)}, {sql_str(mid_init)}, "
        f"{sql_str(ssn)}, {sql_str(birth_dt_str)}, {sql_str(gndr)}, {sql_str(mar_sts)}, "
        f"{sql_str(status_cd)}, {sql_str(hire_dt_str)}, {sql_str(tier)}, {sql_str(plan_cd)}, "
        f"{sql_str(empr[0])}, {sql_str(dept_cd)}, {sql_str(job_class)}, "
        f"{sql_str(orig_sys)}, {sql_str(email)}, "
        f"{sql_str(str(ret_dt)) if ret_dt else 'NULL'}, "
        f"{sql_str(str(death_dt)) if death_dt else 'NULL'}, "
        f"{sql_ts(lst_upd)}, 'SYSTEM');"
    )

    # Store member info for later tables
    members.append({
        "mbr_nbr": mbr_nbr, "hire_dt": hire_dt, "birth_dt": birth_dt,
        "orig_sys": orig_sys, "status_cd": status_cd, "plan_cd": plan_cd,
        "tier": tier, "empr_cd": empr[0], "base_sal": base_sal,
        "yos": yos, "age": age, "ret_dt": ret_dt, "death_dt": death_dt,
        "disability": disability, "terminated": terminated, "vested": vested,
    })

    # Employment spell
    spell_end = ret_dt or death_dt
    if terminated:
        spell_end = rand_date(max(hire_dt.year + 1, 2000), min(2022, hire_dt.year + 20))
    spell_typ = "FT" if random.random() < 0.85 else random.choice(["PT","TMP"])
    fte = 100.00 if spell_typ == "FT" else round(random.uniform(40, 80), 2)
    emit(
        f"INSERT INTO src_prism.PRISM_EMP_SPELL "
        f"(SPELL_ID, MBR_NBR, EMPR_CD, DEPT_CD, JOB_CLASS_CD, SPELL_START, SPELL_END, "
        f"SPELL_TYP, FTE_PCT, TERM_RSN_CD, REHIRE_FLG, SVC_CR_ELIGIBLE) VALUES "
        f"({spell_id}, {mbr_nbr}, {sql_str(empr[0])}, {sql_str(dept_cd)}, {sql_str(job_class)}, "
        f"{sql_date(hire_dt)}, {sql_date(spell_end)}, {sql_str(spell_typ)}, {sql_num(fte)}, "
        f"NULL, NULL, 'Y');"
    )
    spell_id += 1

    # Job history: initial hire record
    emit(
        f"INSERT INTO src_prism.PRISM_JOB_HIST "
        f"(JOB_SEQ, EMPL_ID, EFF_DATE, ACTION_CD, ANNUAL_SAL, EXEMPT_FLG, STD_HRS_WK, "
        f"PAY_FREQ_CD, ENTERED_DT) VALUES "
        f"({job_seq}, {mbr_nbr}, {sql_date(hire_dt)}, "
        f"{''.join([sql_str('INIT') if orig_sys == 'OPUS' else sql_str('HIRE')])}, "
        f"{sql_num(round(base_sal, 2))}, 'Y', 40.00, 'BW', {sql_ts(lst_upd)});"
    )
    job_seq += 1

emit("")

# ---------------------------------------------------------------------------
# Benefit calculations
# ---------------------------------------------------------------------------
emit("-- PRISM_BENEFIT_CALC")
for m in members:
    if m["ret_dt"] or m["disability"]:
        as_of = m["ret_dt"] or datetime.date(2023, 1, 1)
        age_at_ret = (as_of - m["birth_dt"]).days / 365.25
        actual_yos = (as_of - m["hire_dt"]).days / 365.25
        mult = 0.018 if m["tier"] == "T2" else 0.020
        fas_period = 60 if m["hire_dt"] < datetime.date(2003, 1, 1) else 36
        fas = m["base_sal"] * (1.025 ** actual_yos) * random.uniform(1.05, 1.20)
        gross = mult * actual_yos * fas / 12.0
        penalty = min(max((65.0 - age_at_ret) * 0.06, 0.0), 0.30) if age_at_ret < 65 else 0.0
        benefit = max(min(gross * (1 - penalty), fas / 12.0 * 0.75), 800.0)

        calc_type = "D" if m["disability"] else "R"
        ret_type = "DSB" if m["disability"] else ("ERY" if age_at_ret < 65 else "NRM")
        calc_dt = datetime.datetime(as_of.year, as_of.month, min(as_of.day, 28), 10, 0, 0)

        emit(
            f"INSERT INTO src_prism.PRISM_BENEFIT_CALC "
            f"(CALC_ID, MBR_NBR, CALC_DT, CALC_TYPE, AS_OF_DT, CALC_STATUS, "
            f"YOS_USED, FAS_USED, FAS_PERIOD_MO, AGE_AT_CALC, RET_TYPE_CD, "
            f"GROSS_BENEFIT, CALC_RESULT, ERY_REDUCTION, CALC_BY_USR, OVERRIDE_FLG) VALUES "
            f"({calc_id}, {m['mbr_nbr']}, {sql_ts(calc_dt)}, {sql_str(calc_type)}, "
            f"{sql_date(as_of)}, 'C', "
            f"{round(actual_yos, 4)}, {round(fas, 2)}, {fas_period}, {round(age_at_ret, 3)}, "
            f"{sql_str(ret_type)}, {round(gross, 2)}, {round(benefit, 2)}, {round(penalty, 4)}, "
            f"'SYSTEM', 'N');"
        )

        calcs.append({
            "calc_id": calc_id, "mbr_nbr": m["mbr_nbr"],
            "calc_type": calc_type, "as_of_dt": as_of,
            "benefit": round(benefit, 2),
        })
        calc_id += 1

emit("")

# ---------------------------------------------------------------------------
# Salary data: PRISM_SAL_ANNUAL (pre-1998 annual)
# ---------------------------------------------------------------------------
emit("-- PRISM_SAL_ANNUAL (pre-1998, annual)")
for m in members:
    hire_yr_int = m["hire_dt"].year
    if hire_yr_int < 1998:
        for yr in range(hire_yr_int, 1998):
            growth = 1.025 ** (yr - hire_yr_int)
            gross = round(m["base_sal"] * growth, 2)
            contrib = round(gross * 0.085, 2)
            emit(
                f"INSERT INTO src_prism.PRISM_SAL_ANNUAL "
                f"(ANN_SAL_ID, EMP_NBR, TAX_YR, GROSS_EARN, PENSION_EARN, CONTRIB_AMT, "
                f"EMPR_CD, LOAD_SRC, LOAD_DT) VALUES "
                f"({ann_id}, {m['mbr_nbr']}, {yr}, {gross}, {gross}, {contrib}, "
                f"{sql_str(m['empr_cd'])}, 'OPUS_MIGRATION', '1998-01-15');"
            )
            sal_annual.append(ann_id)
            ann_id += 1

emit("")

# ---------------------------------------------------------------------------
# Salary data: PRISM_SAL_PERIOD (post-1998, biweekly)
# ---------------------------------------------------------------------------
emit("-- PRISM_SAL_PERIOD (post-1998, biweekly)")
for m in members:
    hire_yr_int = m["hire_dt"].year
    end_yr_int = 2024
    if m["ret_dt"]:
        end_yr_int = m["ret_dt"].year
    elif m["death_dt"]:
        end_yr_int = m["death_dt"].year
    elif m["terminated"]:
        end_yr_int = random.randint(max(hire_yr_int + 1, 2000), max(2022, hire_yr_int + 2))

    for yr in range(max(hire_yr_int, 1998), min(end_yr_int + 1, 2025)):
        growth = 1.025 ** (yr - hire_yr_int)
        pp = round(m["base_sal"] * growth / 26.0, 2)
        for p in range(26):
            prd_s = datetime.date(yr, 1, 1) + datetime.timedelta(days=p * 14)
            if prd_s.year > yr:
                break
            prd_e = min(prd_s + datetime.timedelta(days=13), datetime.date(yr, 12, 31))
            emit(
                f"INSERT INTO src_prism.PRISM_SAL_PERIOD "
                f"(SAL_PRD_ID, EMP_ID, PRD_START_DT, PRD_END_DT, GROSS_PAY, PENSION_PAY, "
                f"EMPR_CD) VALUES "
                f"({prd_id}, {m['mbr_nbr']}, {sql_date(prd_s)}, {sql_date(prd_e)}, "
                f"{pp}, {pp}, {sql_str(m['empr_cd'])});"
            )
            sal_period.append(prd_id)
            prd_id += 1

emit("")

# ---------------------------------------------------------------------------
# Stats
# ---------------------------------------------------------------------------
status_dist = {}
for m in members:
    status_dist[m["status_cd"]] = status_dist.get(m["status_cd"], 0) + 1

opus_count = sum(1 for m in members if m["orig_sys"] == "OPUS")
print(f"Members:            {len(members)}")
print(f"  OPUS migrated:    {opus_count}")
print(f"  Status dist:      {dict(sorted(status_dist.items()))}")
print(f"Benefit calcs:      {len(calcs)}")
print(f"SAL_ANNUAL rows:    {len(sal_annual)}  (pre-1998, annual only)")
print(f"SAL_PERIOD rows:    {len(sal_period)}  (post-1998, biweekly)")

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
script_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(script_dir, "init", "02_seed.sql")
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(sql_lines))
    f.write("\n")

print(f"\nSaved: {output_path}")
print(f"Total SQL statements: {len([l for l in sql_lines if l.startswith('INSERT')])}")
