"""
PRISM Legacy Data Generator — SQL INSERT output
Generates realistic PRISM pension data with known data quality issues.
Output: init/02_seed.sql with schema-qualified INSERT statements.
"""
import random, datetime, os

random.seed(42)

N_MEMBERS = 100
MIGRATION_BOUNDARY = datetime.date(1998, 1, 1)
SSN_BOUNDARY = datetime.date(2001, 1, 1)
BIRTH_DT_ERROR_RATE = 0.15

EMPLOYERS = [
    ("CITYMAIN", "City of Riverside", "MUNI"),
    ("CNTY01",   "Riverside County", "CNTY"),
    ("SCH001",   "Unified School District", "SCHL"),
    ("UTIL01",   "Municipal Utilities", "SPEC"),
    ("FIRE01",   "Fire District No. 4", "SPEC"),
    ("PARK01",   "Parks & Recreation", "MUNI"),
]

# ---------------------------------------------------------------------------
# SQL helpers
# ---------------------------------------------------------------------------

def sql_str(val):
    """Wrap a string value for SQL. Returns NULL for None."""
    if val is None:
        return "NULL"
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"

def sql_num(val):
    """Numeric literal or NULL."""
    if val is None:
        return "NULL"
    return str(val)

def sql_date(val):
    """Date literal or NULL. Accepts date objects or strings."""
    if val is None:
        return "NULL"
    if isinstance(val, datetime.date):
        return f"'{val.isoformat()}'"
    return f"'{val}'"

def sql_ts(val):
    """Timestamp literal or NULL."""
    if val is None:
        return "NULL"
    if isinstance(val, datetime.datetime):
        return f"'{val.strftime('%Y-%m-%d %H:%M:%S')}'"
    if isinstance(val, datetime.date):
        return f"'{val.isoformat()} 00:00:00'"
    return f"'{val}'"

# ---------------------------------------------------------------------------
# Data helpers (unchanged logic from original generator)
# ---------------------------------------------------------------------------

def rand_date(start_yr, end_yr):
    if start_yr > end_yr:
        end_yr = start_yr
    start = datetime.date(start_yr, 1, 1)
    end = datetime.date(end_yr, 12, 31)
    delta = (end - start).days
    if delta <= 0:
        return start
    return start + datetime.timedelta(days=random.randint(0, delta))

def format_birth_dt(dt, orig_sys):
    if orig_sys == "OPUS" and random.random() < BIRTH_DT_ERROR_RATE:
        return f"{dt.month:02d}{dt.day:02d}{dt.year:04d}"  # wrong: MMDDYYYY
    return dt.strftime("%Y%m%d")

def format_ssn(s, hire_dt):
    return f"{s[:3]}-{s[3:5]}-{s[5:]}" if hire_dt < SSN_BOUNDARY else s

def gen_ssn():
    return str(random.randint(100000000, 999999999))

# ---------------------------------------------------------------------------
# Name pools
# ---------------------------------------------------------------------------

first_names = [
    "James","Mary","Robert","Patricia","Michael","Linda","William","Barbara",
    "David","Elizabeth","Richard","Jennifer","Joseph","Maria","Thomas","Susan",
    "Charles","Margaret","Christopher","Dorothy","Daniel","Lisa","Nancy"
]
last_names = [
    "Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis",
    "Wilson","Taylor","Anderson","Thomas","Jackson","White","Harris","Martin",
    "Thompson","Young","Robinson","Lewis","Walker","Hall","Allen","King"
]

# ---------------------------------------------------------------------------
# Collect SQL statements
# ---------------------------------------------------------------------------
sql_lines = []

def emit(line):
    sql_lines.append(line)

# Header
emit("-- ============================================================")
emit("-- PRISM seed data — auto-generated by prism_data_generator.py")
emit("-- Deterministic seed: 42")
emit(f"-- Members: {N_MEMBERS}")
emit("-- ============================================================")
emit("")
emit("SET search_path TO src_prism;")
emit("")

# ---------------------------------------------------------------------------
# Reference data: PRISM_EMPR_LIST
# ---------------------------------------------------------------------------
emit("-- PRISM_EMPR_LIST")
for empr_cd, empr_nm, empr_typ in EMPLOYERS:
    emit(
        f"INSERT INTO src_prism.PRISM_EMPR_LIST "
        f"(EMPR_CD, EMPR_NM, EMPR_TYP_CD, EMPR_STATUS, JOIN_DT, CONTRIB_RATE) VALUES "
        f"({sql_str(empr_cd)}, {sql_str(empr_nm)}, {sql_str(empr_typ)}, 'A', '1991-01-01', 0.1200);"
    )
emit("")

# ---------------------------------------------------------------------------
# Reference data: PRISM_MISC_CODES (already seeded in DDL, add extras)
# ---------------------------------------------------------------------------
emit("-- PRISM_MISC_CODES — additional codes beyond status codes in DDL")
plan_codes = [
    ("PLAN", "DB_MAIN", "Defined Benefit — Main Plan", "DB Main",  "1991-01-01"),
    ("PLAN", "DB_T2",   "Defined Benefit — Tier 2",    "DB Tier2", "2010-01-01"),
    ("JOBCL", "ADMIN",  "Administrative",               "Admin",    "1991-01-01"),
    ("JOBCL", "PROF",   "Professional",                  "Prof",     "1991-01-01"),
    ("JOBCL", "SAFTY",  "Public Safety",                 "Safety",   "1991-01-01"),
    ("JOBCL", "MGMT",   "Management",                    "Mgmt",     "1991-01-01"),
    ("TRSN",  "VOL",    "Voluntary Termination",         "Vol Term", "1991-01-01"),
    ("TRSN",  "INVL",   "Involuntary Termination",       "Invol",    "1991-01-01"),
    ("TRSN",  "RET",    "Retirement",                    "Retire",   "1991-01-01"),
    ("TRSN",  "DEAT",   "Death",                         "Death",    "1991-01-01"),
]
for code_type, code_val, code_desc, short_desc, eff_dt in plan_codes:
    emit(
        f"INSERT INTO src_prism.PRISM_MISC_CODES "
        f"(CODE_TYPE, CODE_VAL, CODE_DESC, SHORT_DESC, EFF_DT, END_DT, SORT_SEQ, NOTES) VALUES "
        f"({sql_str(code_type)}, {sql_str(code_val)}, {sql_str(code_desc)}, "
        f"{sql_str(short_desc)}, '{eff_dt}', NULL, NULL, NULL);"
    )
emit("")

# ---------------------------------------------------------------------------
# Reference data: PRISM_PLAN_PARAMS
# ---------------------------------------------------------------------------
emit("-- PRISM_PLAN_PARAMS")
plan_params = [
    (1, "DB_MAIN", "1991-01-01", None, 0.0200, 65.0, 55.0, 0.0600, 0.3000, 60, 0.7500, 800.00, 5.0, 0.0850, 0.1200, 0.0300),
    (2, "DB_MAIN", "2003-01-01", None, 0.0200, 65.0, 55.0, 0.0600, 0.3000, 36, 0.7500, 800.00, 5.0, 0.0850, 0.1200, 0.0300),
    (3, "DB_T2",   "2010-01-01", None, 0.0180, 67.0, 57.0, 0.0600, 0.3000, 60, 0.7500, 800.00, 5.0, 0.0900, 0.1200, 0.0200),
]
for p in plan_params:
    emit(
        f"INSERT INTO src_prism.PRISM_PLAN_PARAMS "
        f"(PARAM_ID, PLAN_CD, EFF_DT, END_DT, BENEFIT_MULT, NRM_RET_AGE, ERY_RET_AGE, "
        f"ERY_PENALTY_RT, ERY_MAX_PEN, FAS_PERIOD_MO, MAX_BENEFIT_PCT, MIN_BENEFIT_AMT, "
        f"VESTING_YRS, CONTRIB_RATE_EE, CONTRIB_RATE_ER, COLA_CAP_PCT) VALUES "
        f"({p[0]}, {sql_str(p[1])}, {sql_date(p[2])}, {sql_date(p[3])}, "
        f"{sql_num(p[4])}, {sql_num(p[5])}, {sql_num(p[6])}, {sql_num(p[7])}, "
        f"{sql_num(p[8])}, {sql_num(p[9])}, {sql_num(p[10])}, {sql_num(p[11])}, "
        f"{sql_num(p[12])}, {sql_num(p[13])}, {sql_num(p[14])}, {sql_num(p[15])});"
    )
emit("")

# ---------------------------------------------------------------------------
# Generate members and related data
# ---------------------------------------------------------------------------
members = []
calcs = []
sal_annual = []
sal_period = []

ann_id = prd_id = calc_id = spell_id = job_seq = 1

emit("-- PRISM_MEMBER")
for i in range(N_MEMBERS):
    mbr_nbr = 10000 + i
    hire_yr = random.randint(1965, 2022)
    hire_dt = rand_date(hire_yr, min(hire_yr + 2, 2022))
    birth_yr = hire_yr - random.randint(22, 45)
    birth_yr = max(birth_yr, 1935)
    birth_dt = rand_date(birth_yr, min(birth_yr + 3, hire_yr - 20))

    orig_sys = "OPUS" if hire_dt < MIGRATION_BOUNDARY else None
    today = datetime.date(2025, 1, 1)
    age = (today - birth_dt).days / 365.25
    yos = (today - hire_dt).days / 365.25

    plan_cd = "DB_T2" if hire_dt >= datetime.date(2010, 1, 1) else "DB_MAIN"
    tier = "T2" if plan_cd == "DB_T2" else ("T1" if orig_sys != "OPUS" else None)
    empr = random.choice(EMPLOYERS)
    base_sal = random.randint(38000, 92000)

    ret_dt = death_dt = None
    terminated = on_leave = disability = False
    vested = yos >= 5

    r = random.random()
    # Disability uses a separate draw so it isn't masked by retirement
    r_disb = random.random()
    if r_disb < 0.06 and yos > 5:
        # ~6% of eligible members get disability — independent of retirement path
        disability = True
        ret_dt = rand_date(max(hire_yr + 5, 2000), min(2024, hire_yr + 30))
    elif age > 62 and yos > 20 and r < 0.60:
        ret_yr = min(hire_yr + random.randint(25, 35), 2024)
        ret_dt = rand_date(ret_yr, min(ret_yr + 3, 2024))
        if random.random() < 0.08:
            death_yr = min(ret_yr + random.randint(1, 15), 2024)
            death_dt = rand_date(death_yr, min(death_yr + 2, 2024))
    elif r < 0.12 and not ret_dt:
        terminated = True
    elif r < 0.15 and not ret_dt:
        on_leave = True

    # Status code (overloaded)
    if death_dt:
        status_cd = "D"
    elif disability and ret_dt:
        status_cd = "DI"
    elif ret_dt:
        status_cd = "R"
    elif terminated and vested:
        status_cd = "DE"
    elif terminated:
        status_cd = "I"
    elif on_leave and hire_dt >= datetime.date(2003, 1, 1):
        status_cd = "AL"
    else:
        status_cd = "A"

    ssn = format_ssn(gen_ssn(), hire_dt)
    birth_dt_str = format_birth_dt(birth_dt, orig_sys)
    hire_dt_str = str(hire_dt)
    mid_init = random.choice(["A","B","C","D","E","J","K","L","M","R","S","T", None])
    gndr = random.choice(["M","F",None]) if orig_sys == "OPUS" else random.choice(["M","F"])
    mar_sts = random.choice(["S","M","D","W", None])
    dept_cd = random.choice(["ADM","FIN","IT","OPS","HR","ENG", None])
    job_class = random.choice(["ADMIN","PROF","SAFTY","MGMT", None])
    last_nm = random.choice(last_names)
    first_nm = random.choice(first_names)
    email = f"{first_nm.lower()}.{last_nm.lower()}{mbr_nbr}@example.com" if hire_dt >= datetime.date(2006, 1, 1) else None
    lst_upd = datetime.datetime(2024, random.randint(1,12), random.randint(1,28), random.randint(8,17), random.randint(0,59), 0)

    emit(
        f"INSERT INTO src_prism.PRISM_MEMBER "
        f"(MBR_NBR, LAST_NM, FIRST_NM, MID_INIT, NATL_ID, BIRTH_DT, GNDR_CD, MAR_STS_CD, "
        f"STATUS_CD, HIRE_DT, MBR_TIER, PLAN_CD, EMPR_CD, DEPT_CD, JOB_CLASS_CD, "
        f"ORIG_SYS, EMAIL_ADDR, RET_DT, DEATH_DT, LST_UPD_DT, LST_UPD_USR) VALUES "
        f"({mbr_nbr}, {sql_str(last_nm)}, {sql_str(first_nm)}, {sql_str(mid_init)}, "
        f"{sql_str(ssn)}, {sql_str(birth_dt_str)}, {sql_str(gndr)}, {sql_str(mar_sts)}, "
        f"{sql_str(status_cd)}, {sql_str(hire_dt_str)}, {sql_str(tier)}, {sql_str(plan_cd)}, "
        f"{sql_str(empr[0])}, {sql_str(dept_cd)}, {sql_str(job_class)}, "
        f"{sql_str(orig_sys)}, {sql_str(email)}, "
        f"{sql_str(str(ret_dt)) if ret_dt else 'NULL'}, "
        f"{sql_str(str(death_dt)) if death_dt else 'NULL'}, "
        f"{sql_ts(lst_upd)}, 'SYSTEM');"
    )

    # Store member info for later tables
    members.append({
        "mbr_nbr": mbr_nbr, "hire_dt": hire_dt, "birth_dt": birth_dt,
        "orig_sys": orig_sys, "status_cd": status_cd, "plan_cd": plan_cd,
        "tier": tier, "empr_cd": empr[0], "base_sal": base_sal,
        "yos": yos, "age": age, "ret_dt": ret_dt, "death_dt": death_dt,
        "disability": disability, "terminated": terminated, "vested": vested,
    })

    # Employment spell
    spell_end = ret_dt or death_dt
    if terminated:
        spell_end = rand_date(max(hire_dt.year + 1, 2000), min(2022, hire_dt.year + 20))
    spell_typ = "FT" if random.random() < 0.85 else random.choice(["PT","TMP"])
    fte = 100.00 if spell_typ == "FT" else round(random.uniform(40, 80), 2)
    emit(
        f"INSERT INTO src_prism.PRISM_EMP_SPELL "
        f"(SPELL_ID, MBR_NBR, EMPR_CD, DEPT_CD, JOB_CLASS_CD, SPELL_START, SPELL_END, "
        f"SPELL_TYP, FTE_PCT, TERM_RSN_CD, REHIRE_FLG, SVC_CR_ELIGIBLE) VALUES "
        f"({spell_id}, {mbr_nbr}, {sql_str(empr[0])}, {sql_str(dept_cd)}, {sql_str(job_class)}, "
        f"{sql_date(hire_dt)}, {sql_date(spell_end)}, {sql_str(spell_typ)}, {sql_num(fte)}, "
        f"NULL, NULL, 'Y');"
    )
    spell_id += 1

    # Job history: initial hire record
    emit(
        f"INSERT INTO src_prism.PRISM_JOB_HIST "
        f"(JOB_SEQ, EMPL_ID, EFF_DATE, ACTION_CD, ANNUAL_SAL, EXEMPT_FLG, STD_HRS_WK, "
        f"PAY_FREQ_CD, ENTERED_DT) VALUES "
        f"({job_seq}, {mbr_nbr}, {sql_date(hire_dt)}, "
        f"{''.join([sql_str('INIT') if orig_sys == 'OPUS' else sql_str('HIRE')])}, "
        f"{sql_num(round(base_sal, 2))}, 'Y', 40.00, 'BW', {sql_ts(lst_upd)});"
    )
    job_seq += 1

emit("")

# ---------------------------------------------------------------------------
# Benefit calculations
# ---------------------------------------------------------------------------
emit("-- PRISM_BENEFIT_CALC")
# Early retirement reduction tables from plan-config.yaml
REDUCTION_T12 = {55:0.70, 56:0.73, 57:0.76, 58:0.79, 59:0.82,
                 60:0.85, 61:0.88, 62:0.91, 63:0.94, 64:0.97, 65:1.00}
REDUCTION_T3 = {60:0.70, 61:0.76, 62:0.82, 63:0.88, 64:0.94, 65:1.00}

# Identify ~6 retired/disabled members whose benefit calcs will be SKIPPED.
# These members will still have payment history records (orphan payments) and
# exercise the Tier 2 reconciliation path (payment history without stored calcs).
orphan_calc_count = 0
ORPHAN_CALC_TARGET = 6
orphan_payment_members = []  # will get payments but no stored calc

for m in members:
    if m["ret_dt"] or m["disability"]:
        as_of = m["ret_dt"] or datetime.date(2023, 1, 1)
        age_at_ret = (as_of - m["birth_dt"]).days / 365.25
        actual_yos = (as_of - m["hire_dt"]).days / 365.25
        mult = 0.015 if m["tier"] in ("T2", "T3") else 0.020
        fas_period = 60 if m["hire_dt"] < datetime.date(2003, 1, 1) else 36
        fas = m["base_sal"] * (1.025 ** actual_yos) * random.uniform(1.05, 1.20)
        gross = mult * actual_yos * fas / 12.0
        red_table = REDUCTION_T3 if m["tier"] == "T3" else REDUCTION_T12
        age_int = int(age_at_ret)
        if age_int in red_table:
            reduction = red_table[age_int]
        elif age_int >= 65:
            reduction = 1.0
        else:
            # Below table minimum: clamp to the lowest factor
            reduction = red_table[min(red_table.keys())]
        benefit = max(gross * reduction, 800.0)

        calc_type = "D" if m["disability"] else "R"
        ret_type = "DSB" if m["disability"] else ("ERY" if age_at_ret < 65 else "NRM")
        calc_dt = datetime.datetime(as_of.year, as_of.month, min(as_of.day, 28), 10, 0, 0)

        # Skip benefit calc for a subset — simulates legacy system data gap where
        # payment records exist but no formal benefit calculation was stored.
        if orphan_calc_count < ORPHAN_CALC_TARGET and not m["disability"]:
            orphan_calc_count += 1
            orphan_payment_members.append({
                "mbr_nbr": m["mbr_nbr"], "as_of_dt": as_of,
                "calc_type": calc_type, "benefit": round(benefit, 2),
            })
            continue

        emit(
            f"INSERT INTO src_prism.PRISM_BENEFIT_CALC "
            f"(CALC_ID, MBR_NBR, CALC_DT, CALC_TYPE, AS_OF_DT, CALC_STATUS, "
            f"YOS_USED, FAS_USED, FAS_PERIOD_MO, AGE_AT_CALC, RET_TYPE_CD, "
            f"GROSS_BENEFIT, CALC_RESULT, ERY_REDUCTION, CALC_BY_USR, OVERRIDE_FLG) VALUES "
            f"({calc_id}, {m['mbr_nbr']}, {sql_ts(calc_dt)}, {sql_str(calc_type)}, "
            f"{sql_date(as_of)}, 'C', "
            f"{round(actual_yos, 4)}, {round(fas, 2)}, {fas_period}, {round(age_at_ret, 3)}, "
            f"{sql_str(ret_type)}, {round(gross, 2)}, {round(benefit, 2)}, {round(reduction, 4)}, "
            f"'SYSTEM', 'N');"
        )

        calcs.append({
            "calc_id": calc_id, "mbr_nbr": m["mbr_nbr"],
            "calc_type": calc_type, "as_of_dt": as_of,
            "benefit": round(benefit, 2),
        })
        calc_id += 1

emit("")

# ---------------------------------------------------------------------------
# Payment schedules and payment history (for retirees/disabled with calcs)
# ---------------------------------------------------------------------------
emit("-- PRISM_PMT_SCHEDULE")
pmt_sched_id = 1
pmt_hist_id = 1
pmt_history = []

for c in calcs:
    # One schedule per calc — REGR for regular pension, DISB for disability
    sched_typ = "DISB" if c["calc_type"] == "D" else "REGR"
    eff_dt = c["as_of_dt"]
    net = round(c["benefit"] * 0.78, 2)  # after tax/deductions
    tax_fed = min(round(c["benefit"] * 0.15, 2), 999.99)  # NUMERIC(5,2) cap
    tax_ste = min(round(c["benefit"] * 0.05, 2), 999.99)  # NUMERIC(5,2) cap

    emit(
        f"INSERT INTO src_prism.PRISM_PMT_SCHEDULE "
        f"(PMT_SCHED_ID, MBR_NBR, SCHED_TYP, EFF_DT, MONTHLY_AMT, PAY_FREQ_CD, "
        f"PMT_METHOD, BANK_ABA, BANK_ACCT, TAX_ELECT_FED, TAX_ELECT_STE, "
        f"COLA_ELIGIBLE, LINKED_CALC_ID) VALUES "
        f"({pmt_sched_id}, {c['mbr_nbr']}, {sql_str(sched_typ)}, {sql_date(eff_dt)}, "
        f"{c['benefit']}, 'MO', 'ACH', '021000021', '1234567890', "
        f"{tax_fed}, {tax_ste}, 'Y', {c['calc_id']});"
    )

    this_sched_id = pmt_sched_id
    pmt_sched_id += 1

    # Generate 6-24 monthly payment history records after effective date
    n_payments = random.randint(6, 24)
    for p in range(n_payments):
        pmt_month = eff_dt.month + p
        pmt_year = eff_dt.year + (pmt_month - 1) // 12
        pmt_month = ((pmt_month - 1) % 12) + 1
        if pmt_year > 2024:
            break
        pmt_dt = datetime.date(pmt_year, pmt_month, 1)
        # Small variance on gross amount (COLA adjustments, rounding)
        variance = random.uniform(-2.0, 5.0) if p > 6 else 0.0
        gross_amt = round(c["benefit"] + variance, 2)
        net_amt = round(gross_amt * 0.78, 2)
        # Status: most are 'I' (issued), a few pending, very rare voided
        r = random.random()
        if r < 0.92:
            pmt_status = "I"
        elif r < 0.97:
            pmt_status = "C" if pmt_dt.year >= 2005 else "C"
        else:
            pmt_status = "P"

        emit(
            f"INSERT INTO src_prism.PRISM_PMT_HIST "
            f"(PMT_HIST_ID, PMT_SCHED_ID, MBR_NBR, PAY_PRD_DT, PMT_DT, PMT_STATUS, "
            f"GROSS_AMT, NET_AMT, FED_TAX_WH, STE_TAX_WH, PMT_METHOD) VALUES "
            f"({pmt_hist_id}, {this_sched_id}, {c['mbr_nbr']}, {sql_date(pmt_dt)}, "
            f"{sql_date(pmt_dt + datetime.timedelta(days=random.randint(0, 5)))}, "
            f"{sql_str(pmt_status)}, {gross_amt}, {net_amt}, "
            f"{round(gross_amt * 0.15, 2)}, {round(gross_amt * 0.05, 2)}, 'ACH');"
        )
        pmt_history.append(pmt_hist_id)
        pmt_hist_id += 1

# Orphan payments — members with payment history but no benefit calc.
# These exercise the Tier 2 reconciliation path.
emit("-- ORPHAN PAYMENTS (no benefit calc — Tier 2 test data)")
for om in orphan_payment_members:
    sched_typ = "REGR"
    eff_dt = om["as_of_dt"]
    tax_fed = min(round(om["benefit"] * 0.15, 2), 999.99)
    tax_ste = min(round(om["benefit"] * 0.05, 2), 999.99)

    emit(
        f"INSERT INTO src_prism.PRISM_PMT_SCHEDULE "
        f"(PMT_SCHED_ID, MBR_NBR, SCHED_TYP, EFF_DT, MONTHLY_AMT, PAY_FREQ_CD, "
        f"PMT_METHOD, BANK_ABA, BANK_ACCT, TAX_ELECT_FED, TAX_ELECT_STE, "
        f"COLA_ELIGIBLE, LINKED_CALC_ID) VALUES "
        f"({pmt_sched_id}, {om['mbr_nbr']}, {sql_str(sched_typ)}, {sql_date(eff_dt)}, "
        f"{om['benefit']}, 'MO', 'ACH', '021000021', '1234567890', "
        f"{tax_fed}, {tax_ste}, 'Y', NULL);"
    )
    this_sched_id = pmt_sched_id
    pmt_sched_id += 1

    n_payments = random.randint(6, 12)
    for p in range(n_payments):
        pmt_month = eff_dt.month + p
        pmt_year = eff_dt.year + (pmt_month - 1) // 12
        pmt_month = ((pmt_month - 1) % 12) + 1
        if pmt_year > 2024:
            break
        pmt_dt = datetime.date(pmt_year, pmt_month, 1)
        variance = random.uniform(-2.0, 5.0) if p > 3 else 0.0
        gross_amt = round(om["benefit"] + variance, 2)
        net_amt = round(gross_amt * 0.78, 2)
        emit(
            f"INSERT INTO src_prism.PRISM_PMT_HIST "
            f"(PMT_HIST_ID, PMT_SCHED_ID, MBR_NBR, PAY_PRD_DT, PMT_DT, PMT_STATUS, "
            f"GROSS_AMT, NET_AMT, FED_TAX_WH, STE_TAX_WH, PMT_METHOD) VALUES "
            f"({pmt_hist_id}, {this_sched_id}, {om['mbr_nbr']}, {sql_date(pmt_dt)}, "
            f"{sql_date(pmt_dt + datetime.timedelta(days=random.randint(0, 5)))}, "
            f"'I', {gross_amt}, {net_amt}, "
            f"{round(gross_amt * 0.15, 2)}, {round(gross_amt * 0.05, 2)}, 'ACH');"
        )
        pmt_history.append(pmt_hist_id)
        pmt_hist_id += 1

emit("")

# ---------------------------------------------------------------------------
# Salary data: PRISM_SAL_ANNUAL (pre-1998 annual)
# ---------------------------------------------------------------------------
emit("-- PRISM_SAL_ANNUAL (pre-1998, annual)")
for m in members:
    hire_yr_int = m["hire_dt"].year
    if hire_yr_int < 1998:
        for yr in range(hire_yr_int, 1998):
            growth = 1.025 ** (yr - hire_yr_int)
            gross = round(m["base_sal"] * growth, 2)
            contrib = round(gross * 0.085, 2)
            emit(
                f"INSERT INTO src_prism.PRISM_SAL_ANNUAL "
                f"(ANN_SAL_ID, EMP_NBR, TAX_YR, GROSS_EARN, PENSION_EARN, CONTRIB_AMT, "
                f"EMPR_CD, LOAD_SRC, LOAD_DT) VALUES "
                f"({ann_id}, {m['mbr_nbr']}, {yr}, {gross}, {gross}, {contrib}, "
                f"{sql_str(m['empr_cd'])}, 'OPUS_MIGRATION', '1998-01-15');"
            )
            sal_annual.append(ann_id)
            ann_id += 1

emit("")

# ---------------------------------------------------------------------------
# Salary data: PRISM_SAL_PERIOD (post-1998, biweekly)
# ---------------------------------------------------------------------------
emit("-- PRISM_SAL_PERIOD (post-1998, biweekly)")
for m in members:
    hire_yr_int = m["hire_dt"].year
    end_yr_int = 2024
    if m["ret_dt"]:
        end_yr_int = m["ret_dt"].year
    elif m["death_dt"]:
        end_yr_int = m["death_dt"].year
    elif m["terminated"]:
        end_yr_int = random.randint(max(hire_yr_int + 1, 2000), max(2022, hire_yr_int + 2))

    for yr in range(max(hire_yr_int, 1998), min(end_yr_int + 1, 2025)):
        growth = 1.025 ** (yr - hire_yr_int)
        pp = round(m["base_sal"] * growth / 26.0, 2)
        for p in range(26):
            prd_s = datetime.date(yr, 1, 1) + datetime.timedelta(days=p * 14)
            if prd_s.year > yr:
                break
            prd_e = min(prd_s + datetime.timedelta(days=13), datetime.date(yr, 12, 31))
            emit(
                f"INSERT INTO src_prism.PRISM_SAL_PERIOD "
                f"(SAL_PRD_ID, EMP_ID, PRD_START_DT, PRD_END_DT, GROSS_PAY, PENSION_PAY, "
                f"EMPR_CD) VALUES "
                f"({prd_id}, {m['mbr_nbr']}, {sql_date(prd_s)}, {sql_date(prd_e)}, "
                f"{pp}, {pp}, {sql_str(m['empr_cd'])});"
            )
            sal_period.append(prd_id)
            prd_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_MEMBER_ADDR — address history (1-3 per member)
# ---------------------------------------------------------------------------
emit("-- PRISM_MEMBER_ADDR")
addr_seq = 1

CITIES = [
    ("Riverside",    "CA", "92501"), ("Sacramento",  "CA", "95814"),
    ("Denver",       "CO", "80202"), ("Phoenix",     "AZ", "85001"),
    ("Portland",     "OR", "97201"), ("Seattle",     "WA", "98101"),
    ("Austin",       "TX", "78701"), ("Las Vegas",   "NV", "89101"),
]
STREETS = [
    "100 Main St", "2450 Oak Ave", "789 Elm Blvd", "1122 Pine Dr",
    "3300 Cedar Ln", "456 Maple Ct", "55 Walnut Way", "8901 Birch Rd",
]

for m in members:
    n_addr = random.choices([1, 2, 3], weights=[50, 35, 15])[0]
    addr_types = ["RES"]
    if n_addr >= 2:
        addr_types.append("MAL")
    if n_addr >= 3:
        addr_types.append("CHK")
    for idx, atyp in enumerate(addr_types):
        city, state, zipcd = random.choice(CITIES)
        street = random.choice(STREETS)
        apt = f" Apt {random.randint(1, 400)}" if random.random() < 0.30 else ""
        eff = m["hire_dt"] + datetime.timedelta(days=idx * random.randint(365, 2000))
        # ~15% have malformed zip (truncated or wrong format) for data quality simulation
        if random.random() < 0.15:
            zipcd = zipcd[:3]  # truncated zip like "925" instead of "92501"
        emit(
            f"INSERT INTO src_prism.PRISM_MEMBER_ADDR "
            f"(ADDR_SEQ_NBR, MBR_NBR, ADDR_TYP_CD, ADDR_LINE1, ADDR_LINE2, "
            f"CITY, STATE_CD, ZIP_CD, CNTRY_CD, EFF_DT, END_DT, VRFY_DT) VALUES "
            f"({addr_seq}, {m['mbr_nbr']}, {sql_str(atyp)}, {sql_str(street + apt)}, NULL, "
            f"{sql_str(city)}, {sql_str(state)}, {sql_str(zipcd)}, NULL, "
            f"{sql_date(eff)}, NULL, NULL);"
        )
        addr_seq += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_SVC_CREDIT — running-total service credit balances
# ---------------------------------------------------------------------------
emit("-- PRISM_SVC_CREDIT")
svc_cr_id = 1

for m in members:
    end_dt = m["ret_dt"] or m["death_dt"] or datetime.date(2024, 12, 31)
    if m["terminated"]:
        end_dt = min(end_dt, m["hire_dt"] + datetime.timedelta(days=int(m["yos"] * 365.25)))
    actual_yos = max((end_dt - m["hire_dt"]).days / 365.25, 0)
    svc_cr_bal = round(actual_yos, 4)
    svc_cr_ytd = round(min(actual_yos, 1.0), 4) if not m["ret_dt"] else None

    svc_typ = random.choices(["ACTV", "PRCH", "LMIL"], weights=[92, 5, 3])[0]
    prch_amt = round(random.uniform(5000, 25000), 2) if svc_typ == "PRCH" else None

    emit(
        f"INSERT INTO src_prism.PRISM_SVC_CREDIT "
        f"(SVC_CR_ID, MBR_NBR, AS_OF_DT, SVC_CR_BAL, SVC_CR_YTD, "
        f"SVC_TYP_CD, PRCH_AMT, NOTES, LST_UPD_DT) VALUES "
        f"({svc_cr_id}, {m['mbr_nbr']}, {sql_date(end_dt)}, "
        f"{svc_cr_bal}, {sql_num(svc_cr_ytd)}, {sql_str(svc_typ)}, "
        f"{sql_num(prch_amt)}, NULL, {sql_ts(datetime.datetime(2024, 6, 15, 10, 0, 0))});"
    )
    svc_cr_id += 1

    # OPUS members get an additional 1998-01-01 migration boundary record (P-07)
    if m["orig_sys"] == "OPUS":
        opus_yos = round((datetime.date(1998, 1, 1) - m["hire_dt"]).days / 365.25, 4)
        emit(
            f"INSERT INTO src_prism.PRISM_SVC_CREDIT "
            f"(SVC_CR_ID, MBR_NBR, AS_OF_DT, SVC_CR_BAL, SVC_CR_YTD, "
            f"SVC_TYP_CD, PRCH_AMT, NOTES, LST_UPD_DT) VALUES "
            f"({svc_cr_id}, {m['mbr_nbr']}, '1998-01-01', "
            f"{opus_yos}, NULL, 'ACTV', NULL, "
            f"'OPUS migration balance snapshot', '1998-01-15 00:00:00');"
        )
        svc_cr_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_CONTRIB_LEGACY — pre-1998 annual contributions (P-09: duplicates SAL_ANNUAL.CONTRIB_AMT)
# ---------------------------------------------------------------------------
emit("-- PRISM_CONTRIB_LEGACY (pre-1998, annual — intentional P-09 duplicate)")
ctrib_leg_id = 1

for m in members:
    hire_yr_int = m["hire_dt"].year
    if hire_yr_int < 1998:
        for yr in range(hire_yr_int, 1998):
            growth = 1.025 ** (yr - hire_yr_int)
            gross = round(m["base_sal"] * growth, 2)
            ee_contrib = round(gross * 0.085, 2)
            er_contrib = round(gross * 0.12, 2) if random.random() > 0.40 else None
            contrib_rate = 0.0850 if random.random() > 0.30 else None
            emit(
                f"INSERT INTO src_prism.PRISM_CONTRIB_LEGACY "
                f"(CTRIB_LEG_ID, MBR_NBR, TAX_YR, EE_CONTRIB, ER_CONTRIB, "
                f"CONTRIB_RATE, INT_CREDITED) VALUES "
                f"({ctrib_leg_id}, {m['mbr_nbr']}, {yr}, {ee_contrib}, "
                f"{sql_num(er_contrib)}, {sql_num(contrib_rate)}, NULL);"
            )
            ctrib_leg_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_CONTRIB_HIST — post-1998 monthly contributions
# ---------------------------------------------------------------------------
emit("-- PRISM_CONTRIB_HIST (post-1998, monthly)")
ctrib_seq = 1

for m in members:
    hire_yr_int = m["hire_dt"].year
    end_yr_int = 2024
    if m["ret_dt"]:
        end_yr_int = m["ret_dt"].year
    elif m["death_dt"]:
        end_yr_int = m["death_dt"].year
    elif m["terminated"]:
        end_yr_int = random.randint(max(hire_yr_int + 1, 2000), max(2022, hire_yr_int + 2))

    for yr in range(max(hire_yr_int, 1998), min(end_yr_int + 1, 2025)):
        growth = 1.025 ** (yr - hire_yr_int)
        annual_sal = m["base_sal"] * growth
        ee_monthly = round(annual_sal * 0.085 / 12.0, 2)
        er_monthly = round(annual_sal * 0.12 / 12.0, 2)
        for mo in range(1, 13):
            contrib_prd = datetime.date(yr, mo, 1)
            src_cd = "PAYRL" if random.random() < 0.95 else "ADJST"
            posted_dt = contrib_prd + datetime.timedelta(days=random.randint(5, 20))
            emit(
                f"INSERT INTO src_prism.PRISM_CONTRIB_HIST "
                f"(CTRIB_SEQ, MBR_ID, CONTRIB_PRD, EE_CONTRIB_AMT, ER_CONTRIB_AMT, "
                f"CONTRIB_RATE, PENSION_SAL_BS, INT_AMT, CONTRIB_SRC_CD, POSTED_DT) VALUES "
                f"({ctrib_seq}, {m['mbr_nbr']}, {sql_date(contrib_prd)}, "
                f"{ee_monthly}, {er_monthly}, 0.0850, "
                f"{round(annual_sal / 12.0, 2)}, NULL, {sql_str(src_cd)}, "
                f"{sql_date(posted_dt)});"
            )
            ctrib_seq += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_BENEFICIARY — designations + QDRO overload (P-08)
# ---------------------------------------------------------------------------
emit("-- PRISM_BENEFICIARY")
bene_id = 1
qdro_ord_nbrs = []  # track for PRISM_QDRO cross-reference

BENE_FIRST = ["Sarah","John","Emily","Michael","Anna","David","Maria","James","Karen","Robert"]
BENE_LAST = ["Adams","Baker","Clark","Evans","Fisher","Grant","Hill","Irving","Jensen","Kent"]
RELATIONSHIPS = ["spouse","wife","husband","child","son","daughter","partner","sibling","parent","trust"]

for m in members:
    n_bene = random.choices([1, 2, 3], weights=[55, 30, 15])[0]
    remaining_pct = 100.0
    for b in range(n_bene):
        if b == 0:
            btyp = random.choices(["PRIM","SP","QDRO"], weights=[70, 25, 5])[0]
        elif b == 1:
            btyp = random.choices(["CONT","CHLD","OTHR"], weights=[50, 30, 20])[0]
        else:
            btyp = random.choices(["CONT","CHLD","TRST"], weights=[40, 40, 20])[0]

        if b == n_bene - 1:
            share_pct = remaining_pct
        else:
            share_pct = round(random.uniform(30, 70), 2)
            remaining_pct -= share_pct
        # Intentional ~5% data quality issue: shares don't sum to 100
        if random.random() < 0.05:
            share_pct = round(random.uniform(20, 80), 2)

        is_trust = btyp == "TRST"
        bene_first = None if is_trust else random.choice(BENE_FIRST)
        bene_last = None if is_trust else random.choice(BENE_LAST)
        trust_nm = f"The {m['mbr_nbr']} Family Trust" if is_trust else None
        rel = None if is_trust else random.choice(RELATIONSHIPS)
        bene_ssn = gen_ssn() if random.random() < 0.60 and not is_trust else None
        # P-02: birth date format chaos on beneficiary records
        bene_birth = None
        if not is_trust and random.random() < 0.80:
            byr = random.randint(1940, 2005)
            bdt = rand_date(byr, min(byr + 2, 2005))
            if random.random() < BIRTH_DT_ERROR_RATE:
                bene_birth = f"{bdt.month:02d}{bdt.day:02d}{bdt.year:04d}"
            else:
                bene_birth = bdt.strftime("%Y%m%d")

        qdro_ord = None
        qdro_share_typ = None
        if btyp == "QDRO":
            qdro_ord = f"DRO-{m['mbr_nbr']}-{random.randint(1000, 9999)}"
            qdro_share_typ = random.choice(["PCTG", "DLRM", "OFST"])
            qdro_ord_nbrs.append({"ord_nbr": qdro_ord, "mbr_nbr": m["mbr_nbr"],
                                   "share_typ": qdro_share_typ, "share_pct": share_pct})

        emit(
            f"INSERT INTO src_prism.PRISM_BENEFICIARY "
            f"(BENE_ID, MBR_NBR, BENE_TYP_CD, LAST_NM, FIRST_NM, TRUST_NM, "
            f"NATL_ID, BIRTH_DT, RELATIONSHIP, SHARE_PCT, EFF_DT, REVOC_FLG, "
            f"QDRO_ORD_NBR, QDRO_SHARE_TYP) VALUES "
            f"({bene_id}, {m['mbr_nbr']}, {sql_str(btyp)}, "
            f"{sql_str(bene_last)}, {sql_str(bene_first)}, {sql_str(trust_nm)}, "
            f"{sql_str(bene_ssn)}, {sql_str(bene_birth)}, {sql_str(rel)}, "
            f"{share_pct}, {sql_date(m['hire_dt'] + datetime.timedelta(days=random.randint(30, 365)))}, "
            f"{''.join([sql_str('Y') if btyp == 'QDRO' else sql_str('N')])}, "
            f"{sql_str(qdro_ord)}, {sql_str(qdro_share_typ)});"
        )
        bene_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_QDRO — Qualified Domestic Relations Orders (P-08 overlap)
# ---------------------------------------------------------------------------
emit("-- PRISM_QDRO")
qdro_id = 1

# Include QDRO records from beneficiary table (with ~20% intentionally missing — P-08)
for q in qdro_ord_nbrs:
    if random.random() < 0.80:  # 80% have matching QDRO record
        ord_dt = rand_date(2000, 2022)
        ord_status = random.choices(["Q", "P", "R"], weights=[75, 15, 10])[0]
        ap_last = random.choice(BENE_LAST)
        ap_first = random.choice(BENE_FIRST)
        ap_ssn = gen_ssn() if random.random() < 0.70 else None
        ap_birth = None
        if random.random() < 0.60:
            byr = random.randint(1950, 1990)
            bdt = rand_date(byr, min(byr + 2, 1990))
            ap_birth = bdt.strftime("%Y%m%d")
        share_amt = q["share_pct"] if q["share_typ"] == "PCTG" else round(random.uniform(500, 3000), 4)
        pmt_start = ord_dt + datetime.timedelta(days=random.randint(60, 365))
        emit(
            f"INSERT INTO src_prism.PRISM_QDRO "
            f"(QDRO_ID, MBR_NBR, ORD_NBR, ORD_DT, ORD_STATUS, "
            f"AP_LAST_NM, AP_FIRST_NM, AP_NATL_ID, AP_BIRTH_DT, "
            f"SHARE_TYP, SHARE_AMT, SHARE_EFF_DT, PMT_START_DT, PMT_END_DT, LINKED_PMT_SCHED) VALUES "
            f"({qdro_id}, {q['mbr_nbr']}, {sql_str(q['ord_nbr'])}, {sql_date(ord_dt)}, "
            f"{sql_str(ord_status)}, {sql_str(ap_last)}, {sql_str(ap_first)}, "
            f"{sql_str(ap_ssn)}, {sql_str(ap_birth)}, {sql_str(q['share_typ'])}, "
            f"{share_amt}, {sql_date(ord_dt)}, {sql_date(pmt_start)}, NULL, NULL);"
        )
        qdro_id += 1

# Add some QDRO records with NO matching beneficiary record (P-08: orphan QDROs)
for m in members:
    if m["status_cd"] in ("R", "DI") and random.random() < 0.05:
        orphan_ord = f"DRO-{m['mbr_nbr']}-ORPH"
        ord_dt = rand_date(2005, 2020)
        emit(
            f"INSERT INTO src_prism.PRISM_QDRO "
            f"(QDRO_ID, MBR_NBR, ORD_NBR, ORD_DT, ORD_STATUS, "
            f"AP_LAST_NM, AP_FIRST_NM, AP_NATL_ID, AP_BIRTH_DT, "
            f"SHARE_TYP, SHARE_AMT, SHARE_EFF_DT, PMT_START_DT, PMT_END_DT, LINKED_PMT_SCHED) VALUES "
            f"({qdro_id}, {m['mbr_nbr']}, {sql_str(orphan_ord)}, {sql_date(ord_dt)}, "
            f"'P', {sql_str(random.choice(BENE_LAST))}, {sql_str(random.choice(BENE_FIRST))}, "
            f"NULL, NULL, 'PCTG', 50.0000, {sql_date(ord_dt)}, NULL, NULL, NULL);"
        )
        qdro_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_DISABILITY — disability records
# ---------------------------------------------------------------------------
emit("-- PRISM_DISABILITY")
disb_id = 1

# Build lookup from calcs for disability benefit amounts
disb_calc_map = {c["mbr_nbr"]: c for c in calcs if c["calc_type"] == "D"}

for m in members:
    if m["disability"]:
        disb_eff = m["ret_dt"] or rand_date(max(m["hire_dt"].year + 5, 2000), 2022)
        disb_typ = random.choices(["OCCUP", "NON_O", "PART"], weights=[50, 40, 10])[0]
        disb_benefit = disb_calc_map.get(m["mbr_nbr"], {}).get("benefit")
        disb_pct = round(random.uniform(40, 100), 2) if disb_typ == "PART" else None
        rtw_dt = disb_eff + datetime.timedelta(days=random.randint(365, 1500)) if random.random() < 0.20 else None
        cert_exp = disb_eff + datetime.timedelta(days=random.randint(180, 730))
        ins_carrier = random.choice([None, None, None, "MetLife", "Hartford", "Unum"])

        emit(
            f"INSERT INTO src_prism.PRISM_DISABILITY "
            f"(DISB_ID, MBR_NBR, DISB_EFF_DT, DISB_TYP_CD, DISB_STATUS, "
            f"DISB_BENEFIT, DISB_PCT, RTW_DT, CERT_EXP_DT, INS_CARRIER) VALUES "
            f"({disb_id}, {m['mbr_nbr']}, {sql_date(disb_eff)}, {sql_str(disb_typ)}, "
            f"{''.join([sql_str('R') if rtw_dt else sql_str('A')])}, "
            f"{sql_num(disb_benefit)}, {sql_num(disb_pct)}, {sql_date(rtw_dt)}, "
            f"{sql_date(cert_exp)}, {sql_str(ins_carrier)});"
        )
        disb_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_NOTES — free-text notes
# ---------------------------------------------------------------------------
emit("-- PRISM_NOTES")
note_id = 1

NOTE_TEMPLATES = {
    "GENRL": [
        "Member called to update contact information.",
        "Address verification letter sent, no response received.",
        "Annual statement mailed to address on file.",
        "Member requested copy of benefit estimate.",
    ],
    "CALC":  [
        "Benefit calculation reviewed and approved by supervisor.",
        "FAS recalculated after salary correction for {yr}.",
        "Early retirement reduction applied per plan provisions.",
        "Disability benefit amount confirmed per medical review.",
    ],
    "EXCP":  [
        "Service credit discrepancy of {yrs} years identified during audit.",
        "Contribution record gap found for period {yr1}-{yr2}.",
        "Birth date format inconsistency flagged for manual review.",
        "SSN format does not match expected pattern.",
    ],
    "MIGRT": [
        "Record migrated from OPUS system on 1998-01-15. Original OPUS ID: {oid}.",
        "OPUS salary records loaded as annual totals — per-period detail unavailable.",
        "Pre-1998 service credit balance carried forward as lump sum.",
    ],
    "CORR":  [
        "Corrected hire date from {old} to {new} per HR records.",
        "Status code updated from A to AL per Plan Amendment #31.",
        "Employer code corrected from CITYMAIN to {empr}.",
    ],
    "LGCY":  [
        "Legacy system note: original entry by {usr} on {dt}.",
        "Historical record — no audit trail available pre-1998.",
    ],
}

for m in members:
    n_notes = random.choices([0, 1, 2, 3], weights=[20, 40, 25, 15])[0]
    # OPUS members always get at least 1 MIGRT note
    if m["orig_sys"] == "OPUS" and n_notes == 0:
        n_notes = 1

    types_used = set()
    for _ in range(n_notes):
        if m["orig_sys"] == "OPUS" and "MIGRT" not in types_used:
            ntyp = "MIGRT"
        else:
            ntyp = random.choices(
                ["GENRL", "CALC", "EXCP", "MIGRT", "CORR", "LGCY"],
                weights=[40, 20, 15, 10, 10, 5]
            )[0]
        types_used.add(ntyp)

        template = random.choice(NOTE_TEMPLATES[ntyp])
        # Fill template placeholders
        note_text = template.format(
            yr=random.randint(1998, 2023), yrs=round(random.uniform(0.5, 3.0), 1),
            yr1=random.randint(1995, 2010), yr2=random.randint(2011, 2023),
            oid=f"OPUS-{m['mbr_nbr']}", old="1985-01-15", new="1985-02-01",
            empr=m["empr_cd"], usr="JSMITH", dt="1997-06-15",
        )
        note_dt = datetime.datetime(
            random.randint(1998, 2024), random.randint(1, 12),
            random.randint(1, 28), random.randint(8, 17), random.randint(0, 59), 0
        )
        entered_by = random.choice(["JSMITH", "MWILSON", "KPATEL", "SYSTEM", "LGARCIA", None])

        emit(
            f"INSERT INTO src_prism.PRISM_NOTES "
            f"(NOTE_ID, MBR_NBR, NOTE_DT, NOTE_TYP_CD, NOTE_TEXT, ENTERED_BY) VALUES "
            f"({note_id}, {m['mbr_nbr']}, {sql_ts(note_dt)}, {sql_str(ntyp)}, "
            f"{sql_str(note_text)}, {sql_str(entered_by)});"
        )
        note_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_LIFE_EVENTS — life event triggers
# ---------------------------------------------------------------------------
emit("-- PRISM_LIFE_EVENTS")
event_id = 1

for m in members:
    events = []
    # Every member gets HIRE
    events.append(("HIRE", m["hire_dt"], "C", None, None))

    if m["ret_dt"] and not m["disability"]:
        events.append(("RETIR", m["ret_dt"], "C", None, None))
    if m["disability"]:
        disb_dt = m["ret_dt"] or rand_date(max(m["hire_dt"].year + 5, 2000), 2022)
        events.append(("DISB_ON", disb_dt, "C", None, None))
    if m["death_dt"]:
        events.append(("DEATH", m["death_dt"], "C", None, None))
    if m["terminated"]:
        term_dt = rand_date(max(m["hire_dt"].year + 1, 2000), min(2022, m["hire_dt"].year + 20))
        events.append(("TERM", term_dt, "C", None, None))

    # Random additional events
    if random.random() < 0.10:
        events.append(("ADDR_CHG", rand_date(2005, 2023), "C", None, "Address updated via web portal"))
    if random.random() < 0.05:
        events.append(("BENE_CHG", rand_date(2005, 2023), "C", None, "Beneficiary designation updated"))
    if random.random() < 0.03:
        events.append(("NAME_CHG", rand_date(2005, 2023), "C", None, "Name change per court order"))

    for evt_typ, evt_dt, evt_status, related_id, notes in events:
        # ~3% pending events
        if random.random() < 0.03:
            evt_status = "P"
        eff_dt = evt_dt + datetime.timedelta(days=random.randint(0, 30)) if random.random() < 0.70 else evt_dt
        proc_by = random.choice(["JSMITH", "MWILSON", "KPATEL", "SYSTEM", None])
        proc_dt = datetime.datetime(evt_dt.year, min(evt_dt.month, 12),
                                     min(evt_dt.day, 28), 14, 0, 0) if proc_by else None
        emit(
            f"INSERT INTO src_prism.PRISM_LIFE_EVENTS "
            f"(EVENT_ID, MBR_NBR, EVENT_DT, EVENT_TYP_CD, EVENT_STATUS, "
            f"EFF_DT, RELATED_ID, RELATED_TBL, NOTES, PROC_BY, PROC_DT) VALUES "
            f"({event_id}, {m['mbr_nbr']}, {sql_date(evt_dt)}, {sql_str(evt_typ)}, "
            f"{sql_str(evt_status)}, {sql_date(eff_dt)}, {sql_num(related_id)}, "
            f"NULL, {sql_str(notes)}, {sql_str(proc_by)}, {sql_ts(proc_dt)});"
        )
        event_id += 1

emit("")

# ---------------------------------------------------------------------------
# PRISM_COLA_HIST — COLA adjustment history (retirees/disabled only)
# ---------------------------------------------------------------------------
emit("-- PRISM_COLA_HIST")
cola_id = 1
COLA_CAP = 0.03  # 3% plan cap

for c in calcs:
    # Find the member's retirement/disability effective date
    as_of = c["as_of_dt"]
    start_yr = as_of.year + 1  # first COLA is the year after retirement
    current_amt = c["benefit"]
    banked = 0.0

    for yr in range(start_yr, 2025):
        cpi_rate = round(random.uniform(0.005, 0.045), 4)  # 0.5% to 4.5%
        applied_rate = min(cpi_rate, COLA_CAP)
        if cpi_rate > COLA_CAP:
            banked_rate = round(cpi_rate - COLA_CAP, 4)
        else:
            # Use banked amount if CPI is low
            use_banked = min(banked, COLA_CAP - cpi_rate)
            applied_rate = round(cpi_rate + use_banked, 4)
            banked_rate = round(-use_banked, 4) if use_banked > 0 else 0.0
            banked -= use_banked

        if cpi_rate > COLA_CAP:
            banked += cpi_rate - COLA_CAP

        pre_cola = round(current_amt, 2)
        post_cola = round(current_amt * (1 + applied_rate), 2)
        current_amt = post_cola

        emit(
            f"INSERT INTO src_prism.PRISM_COLA_HIST "
            f"(COLA_ID, MBR_NBR, COLA_EFF_DT, PRE_COLA_AMT, COLA_RATE_APPL, "
            f"CPI_RATE, BANKED_RATE, POST_COLA_AMT) VALUES "
            f"({cola_id}, {c['mbr_nbr']}, '{yr}-01-01', "
            f"{pre_cola}, {applied_rate}, {cpi_rate}, "
            f"{round(banked_rate, 4)}, {post_cola});"
        )
        cola_id += 1

emit("")

# ---------------------------------------------------------------------------
# Stats
# ---------------------------------------------------------------------------
status_dist = {}
for m in members:
    status_dist[m["status_cd"]] = status_dist.get(m["status_cd"], 0) + 1

opus_count = sum(1 for m in members if m["orig_sys"] == "OPUS")
import sys as _sys
print(f"Members:            {len(members)}", file=_sys.stderr)
print(f"  OPUS migrated:    {opus_count}", file=_sys.stderr)
print(f"  Status dist:      {dict(sorted(status_dist.items()))}", file=_sys.stderr)
print(f"MEMBER_ADDR rows:   {addr_seq - 1}", file=_sys.stderr)
print(f"EMP_SPELL rows:     {spell_id - 1}", file=_sys.stderr)
print(f"JOB_HIST rows:      {job_seq - 1}", file=_sys.stderr)
print(f"SAL_ANNUAL rows:    {len(sal_annual)}  (pre-1998, annual only)", file=_sys.stderr)
print(f"SAL_PERIOD rows:    {len(sal_period)}  (post-1998, biweekly)", file=_sys.stderr)
print(f"SVC_CREDIT rows:    {svc_cr_id - 1}", file=_sys.stderr)
print(f"CONTRIB_LEGACY:     {ctrib_leg_id - 1}  (pre-1998, annual)", file=_sys.stderr)
print(f"CONTRIB_HIST rows:  {ctrib_seq - 1}  (post-1998, monthly)", file=_sys.stderr)
print(f"Benefit calcs:      {len(calcs)}", file=_sys.stderr)
print(f"PMT_SCHEDULE rows:  {pmt_sched_id - 1}", file=_sys.stderr)
print(f"PMT_HIST rows:      {len(pmt_history)}", file=_sys.stderr)
print(f"BENEFICIARY rows:   {bene_id - 1}", file=_sys.stderr)
print(f"QDRO rows:          {qdro_id - 1}", file=_sys.stderr)
print(f"DISABILITY rows:    {disb_id - 1}", file=_sys.stderr)
print(f"NOTES rows:         {note_id - 1}", file=_sys.stderr)
print(f"LIFE_EVENTS rows:   {event_id - 1}", file=_sys.stderr)
print(f"COLA_HIST rows:     {cola_id - 1}", file=_sys.stderr)

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
script_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(script_dir, "init", "02_seed.sql")
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(sql_lines))
    f.write("\n")

print(f"\nSaved: {output_path}", file=_sys.stderr)
print(f"Total SQL statements: {len([l for l in sql_lines if l.startswith('INSERT')])}", file=_sys.stderr)
