import { describe, it, expect, vi } from 'vitest';
import { screen } from '@testing-library/react';
import { renderWithProviders } from '@/test/helpers';
import CorrespondenceDetail from '../CorrespondenceDetail';
import { mockCorrespondence } from '@/components/dashboard/__tests__/fixtures';

// Mock useSpawnAnimation to skip real animations
vi.mock('@/hooks/useSpawnAnimation', () => ({
  useSpawnAnimation: () => ({
    panelRef: { current: null },
    isVisible: true,
    phase: 'open',
    open: vi.fn(),
    close: vi.fn(),
    style: { transform: 'none', opacity: 1, transition: 'none' },
    DURATION_MS: 0,
  }),
}));

const defaultProps = {
  item: mockCorrespondence[0],
  sourceRect: new DOMRect(100, 200, 600, 40),
  onClose: vi.fn(),
  items: mockCorrespondence,
  currentIndex: 0,
  onNavigate: vi.fn(),
};

describe('CorrespondenceDetail', () => {
  it('renders subject as title', () => {
    renderWithProviders(<CorrespondenceDetail {...defaultProps} />);
    expect(screen.getByText('Retirement Benefit Estimate')).toBeInTheDocument();
  });

  it('renders status badge', () => {
    renderWithProviders(<CorrespondenceDetail {...defaultProps} />);
    const sentElements = screen.getAllByText('sent');
    // StatusBadge + metadata grid both show status
    expect(sentElements.length).toBeGreaterThanOrEqual(1);
  });

  it('renders metadata fields (Generated By, Template)', () => {
    renderWithProviders(<CorrespondenceDetail {...defaultProps} />);
    expect(screen.getByText('Generated By')).toBeInTheDocument();
    expect(screen.getByText('Benefits Team')).toBeInTheDocument();
    expect(screen.getByText('Template ID')).toBeInTheDocument();
    expect(screen.getByText('TPL-001')).toBeInTheDocument();
  });

  it('renders merge data section with key-value pairs', () => {
    renderWithProviders(<CorrespondenceDetail {...defaultProps} />);
    expect(screen.getByText('Merge Fields')).toBeInTheDocument();
    expect(screen.getByText('member_name')).toBeInTheDocument();
    expect(screen.getByText('Robert Martinez')).toBeInTheDocument();
  });

  it('renders body preview with HTML tags stripped', () => {
    renderWithProviders(<CorrespondenceDetail {...defaultProps} />);
    expect(screen.getByText('Body Preview')).toBeInTheDocument();
    expect(screen.getByText('Your estimated monthly benefit is $5,206.55')).toBeInTheDocument();
    // Should not contain HTML tags
    expect(screen.queryByText(/<p>/)).not.toBeInTheDocument();
  });

  it('renders navigation counter "1 of 3"', () => {
    renderWithProviders(<CorrespondenceDetail {...defaultProps} />);
    expect(screen.getByText('1 of 3')).toBeInTheDocument();
  });

  it('renders draft item without sent date', () => {
    const draftItem = mockCorrespondence[1]; // status: 'draft', no sentAt
    renderWithProviders(
      <CorrespondenceDetail {...defaultProps} item={draftItem} currentIndex={1} />,
    );
    expect(screen.getByText(/Created/)).toBeInTheDocument();
    expect(screen.queryByText(/Sent/)).not.toBeInTheDocument();
  });
});
