package profiler

import (
	"database/sql"

	"github.com/noui/platform/migration/mapper"
)

// CanonicalFieldCoverage represents how well a single canonical field is satisfied
// by available source columns.
type CanonicalFieldCoverage struct {
	CanonicalTable  string            `json:"canonical_table"`
	CanonicalColumn string            `json:"canonical_column"`
	Required        bool              `json:"required"`
	DataTypeFamily  string            `json:"data_type_family"`
	Status          string            `json:"status"`          // "COVERED", "TRANSFORMABLE", "UNCOVERED"
	Candidates      []SourceCandidate `json:"candidates"`      // ranked source columns
	BestConfidence  float64           `json:"best_confidence"` // highest candidate confidence
}

// SourceCandidate represents a source column that could satisfy a canonical field.
type SourceCandidate struct {
	SourceTable    string  `json:"source_table"`
	SourceColumn   string  `json:"source_column"`
	Confidence     float64 `json:"confidence"`
	MatchMethod    string  `json:"match_method"` // "TEMPLATE", "SIGNAL", "BOTH"
	TypeCompatible bool    `json:"type_compatible"`
}

// CoverageReport is the target-anchored coverage assessment for an engagement.
type CoverageReport struct {
	EngagementID   string                   `json:"engagement_id"`
	TotalCanonical int                      `json:"total_canonical"`
	Covered        int                      `json:"covered"`       // best_confidence > 0.7
	Transformable  int                      `json:"transformable"` // 0.3 < best_confidence <= 0.7
	Uncovered      int                      `json:"uncovered"`     // best_confidence <= 0.3 or no candidate
	CoverageRate   float64                  `json:"coverage_rate"` // covered / total
	RequiredGaps   int                      `json:"required_gaps"` // uncovered AND required
	Fields         []CanonicalFieldCoverage `json:"fields"`
}

// FieldMappingRow is the subset of field_mapping data needed for coverage analysis.
// Decoupled from DB layer to keep profiler testable without DB imports.
type FieldMappingRow struct {
	SourceTable        string
	SourceColumn       string
	CanonicalTable     string
	CanonicalColumn    string
	TemplateConfidence *float64
	SignalConfidence   *float64
	AgreementStatus    string
}

// SourceColumnInfo is a discovered source column used for similarity-based candidate scoring.
type SourceColumnInfo struct {
	Table    string
	Column   string
	DataType string
}

// ComputeCoverage generates a target-anchored coverage report. It iterates all canonical
// fields defined in the mapper Registry and checks how well existing field mappings (or
// source column similarity) can satisfy each one.
//
// If existingMappings is non-empty, candidates come from approved/proposed mappings.
// If empty, candidates are generated by scoring sourceColumns against template slots.
func ComputeCoverage(
	engagementID string,
	registry *mapper.Registry,
	existingMappings []FieldMappingRow,
	sourceColumns []SourceColumnInfo,
) *CoverageReport {
	report := &CoverageReport{
		EngagementID: engagementID,
		Fields:       make([]CanonicalFieldCoverage, 0),
	}

	// Build mapping index: canonical_table.canonical_column → []FieldMappingRow
	mappingIdx := make(map[string][]FieldMappingRow)
	for _, m := range existingMappings {
		key := m.CanonicalTable + "." + m.CanonicalColumn
		mappingIdx[key] = append(mappingIdx[key], m)
	}

	for _, tag := range registry.Tags() {
		tmpl, ok := registry.Get(tag)
		if !ok || tmpl.CanonicalTable == "" {
			continue // non-pension concepts with no canonical table
		}

		for _, slot := range tmpl.Slots {
			field := CanonicalFieldCoverage{
				CanonicalTable:  tmpl.CanonicalTable,
				CanonicalColumn: slot.CanonicalColumn,
				Required:        slot.Required,
				DataTypeFamily:  slot.DataTypeFamily,
				Candidates:      make([]SourceCandidate, 0),
			}

			key := tmpl.CanonicalTable + "." + slot.CanonicalColumn

			// Check existing mappings first.
			if mappings, ok := mappingIdx[key]; ok {
				for _, m := range mappings {
					conf := bestConfidence(m.TemplateConfidence, m.SignalConfidence)
					method := agreementToMethod(m.AgreementStatus)
					field.Candidates = append(field.Candidates, SourceCandidate{
						SourceTable:    m.SourceTable,
						SourceColumn:   m.SourceColumn,
						Confidence:     conf,
						MatchMethod:    method,
						TypeCompatible: true, // mapping exists, so types were validated
					})
					if conf > field.BestConfidence {
						field.BestConfidence = conf
					}
				}
			} else if len(sourceColumns) > 0 {
				// No mappings exist — use similarity scoring against source columns.
				for _, sc := range sourceColumns {
					sim := mapper.ColumnNameSimilarity(sc.Column, slot.CanonicalColumn)
					// Also check against expected names.
					for _, expected := range slot.ExpectedNames {
						s := mapper.ColumnNameSimilarity(sc.Column, expected)
						if s > sim {
							sim = s
						}
					}
					if sim < 0.3 {
						continue // too low to be a candidate
					}
					typOK := mapper.TypeCompatible(sc.DataType, slot.DataTypeFamily)
					field.Candidates = append(field.Candidates, SourceCandidate{
						SourceTable:    sc.Table,
						SourceColumn:   sc.Column,
						Confidence:     sim,
						MatchMethod:    "SIMILARITY",
						TypeCompatible: typOK,
					})
					if sim > field.BestConfidence {
						field.BestConfidence = sim
					}
				}
			}

			// Classify coverage status.
			switch {
			case field.BestConfidence > 0.7:
				field.Status = "COVERED"
				report.Covered++
			case field.BestConfidence > 0.3:
				field.Status = "TRANSFORMABLE"
				report.Transformable++
			default:
				field.Status = "UNCOVERED"
				report.Uncovered++
				if slot.Required {
					report.RequiredGaps++
				}
			}

			// Sort candidates by confidence descending.
			sortCandidates(field.Candidates)

			report.Fields = append(report.Fields, field)
			report.TotalCanonical++
		}
	}

	if report.TotalCanonical > 0 {
		report.CoverageRate = float64(report.Covered) / float64(report.TotalCanonical)
	}

	return report
}

// ComputeCoverageFromDB is a convenience wrapper that queries field_mapping rows from
// the database and delegates to ComputeCoverage.
func ComputeCoverageFromDB(
	db *sql.DB,
	engagementID string,
	registry *mapper.Registry,
	sourceColumns []SourceColumnInfo,
) (*CoverageReport, error) {
	mappings, err := queryFieldMappings(db, engagementID)
	if err != nil {
		return nil, err
	}
	return ComputeCoverage(engagementID, registry, mappings, sourceColumns), nil
}

// queryFieldMappings fetches all field mappings for an engagement.
func queryFieldMappings(db *sql.DB, engagementID string) ([]FieldMappingRow, error) {
	rows, err := db.Query(
		`SELECT source_table, source_column, canonical_table, canonical_column,
		        template_confidence, signal_confidence, agreement_status
		 FROM migration.field_mapping
		 WHERE engagement_id = $1`,
		engagementID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var mappings []FieldMappingRow
	for rows.Next() {
		var m FieldMappingRow
		if err := rows.Scan(&m.SourceTable, &m.SourceColumn, &m.CanonicalTable,
			&m.CanonicalColumn, &m.TemplateConfidence, &m.SignalConfidence,
			&m.AgreementStatus); err != nil {
			return nil, err
		}
		mappings = append(mappings, m)
	}
	return mappings, rows.Err()
}

func bestConfidence(tmpl, signal *float64) float64 {
	var best float64
	if tmpl != nil && *tmpl > best {
		best = *tmpl
	}
	if signal != nil && *signal > best {
		best = *signal
	}
	return best
}

func agreementToMethod(status string) string {
	switch status {
	case "AGREED":
		return "BOTH"
	case "TEMPLATE_ONLY":
		return "TEMPLATE"
	case "SIGNAL_ONLY":
		return "SIGNAL"
	default:
		return status
	}
}

func sortCandidates(candidates []SourceCandidate) {
	for i := 0; i < len(candidates); i++ {
		for j := i + 1; j < len(candidates); j++ {
			if candidates[j].Confidence > candidates[i].Confidence {
				candidates[i], candidates[j] = candidates[j], candidates[i]
			}
		}
	}
}
