import type { Correspondence } from '@/types/Correspondence';
import { DetailOverlay, MetadataGrid, Section, StatusBadge } from '@/components/DetailOverlay';

export interface CorrespondenceDetailProps {
  item: Correspondence;
  sourceRect: DOMRect;
  onClose: () => void;
  items: Correspondence[];
  currentIndex: number;
  onNavigate: (newIndex: number) => void;
}

const STATUS_COLORS: Record<string, string> = {
  sent: 'bg-emerald-50 text-emerald-700',
  final: 'bg-blue-50 text-blue-700',
  draft: 'bg-gray-100 text-gray-600',
  void: 'bg-red-50 text-red-700',
};

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '');
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export default function CorrespondenceDetail({
  item,
  sourceRect,
  onClose,
  items,
  currentIndex,
  onNavigate,
}: CorrespondenceDetailProps) {
  const subtitle = item.sentAt
    ? `Sent ${formatDate(item.sentAt)}`
    : `Created ${formatDate(item.createdAt)}`;

  const mergeEntries = Object.entries(item.mergeData);

  return (
    <DetailOverlay
      sourceRect={sourceRect}
      onClose={onClose}
      totalItems={items.length}
      currentIndex={currentIndex}
      onNavigate={onNavigate}
      icon={
        <span role="img" aria-label="correspondence">
          📧
        </span>
      }
      title={item.subject}
      subtitle={subtitle}
      statusBadge={<StatusBadge status={item.status} colorMap={STATUS_COLORS} />}
    >
      {/* Metadata */}
      <MetadataGrid
        fields={[
          { label: 'Status', value: item.status },
          { label: 'Generated By', value: item.generatedBy },
          { label: 'Template ID', value: item.templateId },
          { label: 'Sent Via', value: item.sentVia },
          { label: 'Delivery Address', value: item.deliveryAddress },
          { label: 'Case ID', value: item.caseId },
        ]}
      />

      {/* Merge Fields */}
      {mergeEntries.length > 0 && (
        <Section title="Merge Fields">
          <div className="rounded-md border border-gray-200 overflow-hidden">
            <table className="w-full text-sm">
              <tbody className="divide-y divide-gray-100">
                {mergeEntries.map(([key, value]) => (
                  <tr key={key}>
                    <td className="px-3 py-2 text-gray-500 font-mono text-xs bg-gray-50 w-1/3">
                      {key}
                    </td>
                    <td className="px-3 py-2 text-gray-800">{value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>
      )}

      {/* Body Preview */}
      <Section title="Body Preview">
        <div className="rounded-md border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-700 whitespace-pre-wrap">
          {stripHtml(item.bodyRendered)}
        </div>
      </Section>
    </DetailOverlay>
  );
}
